# 1. Importação das bibliotecas necessárias

Nesta etapa são importadas as bibliotecas que serão utilizadas ao longo do projeto para manipulação dos dados, visualização gráfica, treinamento do modelo de Regressão Linear e avaliação de desempenho.

In [2]:
# 1. importação das bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

plt.style.use("seaborn-v0_8")
sns.set_theme(style="whitegrid")

pd.set_option("display.max_columns", None)

## 2. carregamento do dataset

Nesta etapa é realizado o carregamento do conjunto de dados **Auto MPG**, que será utilizado para treinar e avaliar o modelo de regressão linear. Em seguida, exibi as primeiras linhas pra verificar se os dados foram carregados corretamente.

In [3]:
# carrega o dataset Auto MPG
df = sns.load_dataset("mpg")

# exibe as cinco primeiras linhas
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

## 3. análise exploratória dos dados

Nesta etapa são analisadas as principais características do conjunto de dados. O objetivo é compreender sua estrutura, verificar os tipos das variáveis, identificar possíveis valores ausentes e obter estatísticas descritivas antes do pré-processamento.

In [6]:
# exibindo as dimensões do dataset
print(f"Linhas: {df.shape[0]}")
print(f"Colunas: {df.shape[1]}")

Linhas: 398
Colunas: 9

In [5]:
# exibindo informações gerais do dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [7]:
# exibindo estatísticas das variáveis numéricas
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [8]:
# verifica a quantidade de valores ausentes
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [9]:
# exibe os tipos de dados de cada coluna
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
name             object
dtype: object

### Considerações

A análise exploratória permitiu conhecer a estrutura do dataset, identificar os tipos de dados e verificar a existência de valores ausentes. Foi observado que apenas a coluna **horsepower** possui valores nulos, enquanto as demais estão completas. Essas informações servirão de base para a etapa de pré-processamento dos dados.

## 4. tratamento de valores ausentes e preparação dos dados

Nesta etapa tratei os valores ausentes e realizadas as adequações necessárias para preparar o conjunto de dados antes do treinamento do modelo.

In [10]:
# removendo os registros com valores ausentes
df = df.dropna()

# verificando se ainda existem valores nulos
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [ ]:
# removendo a coluna com o nome dos veículos
df = df.drop(columns="name")

# exibindo as primeiras linhas
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [12]:
# convertendo a variável categórica em variáveis dummy
df = pd.get_dummies(df, columns=["origin"], drop_first=True)

# exibindo as primeiras linhas
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,False,True
1,15.0,8,350.0,165.0,3693,11.5,70,False,True
2,18.0,8,318.0,150.0,3436,11.0,70,False,True
3,16.0,8,304.0,150.0,3433,12.0,70,False,True
4,17.0,8,302.0,140.0,3449,10.5,70,False,True

### Considerações

Após o tratamento dos valores ausentes e a preparação das variáveis, o conjunto de dados está pronto para a separação entre as variáveis de entrada e a variável alvo, permitindo o treinamento do modelo de regressão linear.

## 5. separação entre variáveis de entrada (X) e variável alvo (y)

Nesta etapa defini as variáveis de entrada (X), utilizadas para realizar as previsões, e a variável alvo (y), que representa o consumo de combustível dos veículos.

In [ ]:
# separando as variáveis de entrada (X) e a variável alvo (y)
X = df.drop(columns="mpg")
y = df["mpg"]

# exibe as dimensões dos conjuntos
print(f"X: {X.shape}")
print(f"y: {y.shape}")

X: (392, 8)
y: (392,)

### Considerações

A variável **mpg** foi definida como alvo do modelo, enquanto as demais características dos veículos serão utilizadas como variáveis de entrada para realizar as previsões.

## 6. divisão dos dados em conjuntos de treinamento e teste

Nesta etapa, o conjunto de dados é dividido em duas partes: uma para o treinamento do modelo e outra para testar seu desempenho em dados que não foram utilizados durante o treinamento.

In [14]:
# dividindo os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# exibe as dimensões dos conjuntos
print(f"X_train: {X_train.shape}")
print(f"X_test: {X_test.shape}")
print(f"y_train: {y_train.shape}")
print(f"y_test: {y_test.shape}")

X_train: (313, 8)
X_test: (79, 8)
y_train: (313,)
y_test: (79,)

Foram utilizados **80%** dos dados para treinamento e **20%** para teste. O parâmetro `random_state=42` foi definido para garantir que a divisão seja reproduzida da mesma forma em diferentes execuções.

## 7. treinamento do modelo de regressão linear

Nesta etapa, o modelo de Regressão Linear é treinado utilizando o conjunto de treinamento, aprendendo a relação entre as características dos veículos e o consumo de combustível.

In [15]:
# criando o modelo de regressão linear
modelo = LinearRegression()

# treinando o modelo
modelo.fit(X_train, y_train)

LinearRegression()

Após o treinamento, o modelo está preparado para realizar previsões utilizando dados que não foram vistos durante a etapa de treinamento.

## 8. realização das previsões

Nesta etapa, o modelo treinado é utilizado para realizar previsões sobre o conjunto de teste, permitindo comparar os valores previstos com os valores reais.

In [16]:
# realiza as previsões no conjunto de teste
y_pred = modelo.predict(X_test)

# compara alguns valores reais com os previstos
resultado = pd.DataFrame({
    "Valor real": y_test.values,
    "Valor previsto": y_pred
})

resultado.head(10)

   Valor real  Valor previsto
0        26.0       26.623086
1        21.6       26.902469
2        36.1       34.265982
3        26.0       24.441176
4        27.0       28.235414
5        28.0       30.182539
6        13.0        8.561005
7        26.0       30.349163
8        19.0       20.381536
9        29.0       29.446287

As previsões geradas pelo modelo serão utilizadas na próxima etapa para avaliar seu desempenho por meio de métricas de regressão.

## 9. avaliação do desempenho do modelo utilizando métricas de regressão

Nesta etapa, o desempenho do modelo é avaliado por meio de métricas que medem o erro das previsões e a capacidade do modelo de explicar a variação dos dados.

In [17]:
# calcula as métricas de avaliação
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# exibe os resultados
print(f"MAE : {mae:.2f}")
print(f"MSE : {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²  : {r2:.4f}")

MAE : 2.46
MSE : 10.60
RMSE: 3.26
R²  : 0.7923

## 10. análise e interpretação dos resultados obtidos

Com base nas métricas calculadas, é possível analisar o desempenho do modelo na previsão do consumo de combustível dos veículos.

### Análise dos resultados

O modelo apresentou um **R² de 0,7923**, indicando que aproximadamente **79% da variação** no consumo de combustível foi explicada pelas variáveis utilizadas. Esse resultado demonstra um bom ajuste para um modelo de Regressão Linear.

Além disso, o **MAE de 2,46 MPG** e o **RMSE de 3,26 MPG** mostram que, em média, as previsões ficaram próximas dos valores reais, embora ainda existam alguns erros de estimativa.

De forma geral, os resultados indicam que o modelo foi capaz de capturar a relação entre as características dos veículos e o consumo de combustível, apresentando um desempenho satisfatório para este conjunto de dados.